/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertType = IDL.Variant({
  'flood' : IDL.Null,
  'earthquake' : IDL.Null,
  'storm' : IDL.Null,
  'cyclone' : IDL.Null,
});
export const Severity = IDL.Variant({
  'warning' : IDL.Null,
  'danger' : IDL.Null,
  'safe' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : AlertType,
  'title' : IDL.Text,
  'affectedArea' : IDL.Text,
  'recommendedActions' : IDL.Vec(IDL.Text),
  'affectedPopulation' : IDL.Nat,
  'severity' : Severity,
  'issuedAt' : Timestamp,
  'location' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ResourceType = IDL.Variant({
  'hospital' : IDL.Null,
  'fire' : IDL.Null,
  'supply' : IDL.Null,
  'shelter' : IDL.Null,
  'police' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'resourceType' : ResourceType,
  'address' : IDL.Text,
  'hoursOfOperation' : IDL.Text,
  'phone' : IDL.Text,
});
export const WeatherCondition = IDL.Variant({
  'cloudy' : IDL.Null,
  'stormy' : IDL.Null,
  'sunny' : IDL.Null,
  'rainy' : IDL.Null,
});
export const ForecastEntry = IDL.Record({
  'time' : IDL.Text,
  'condition' : WeatherCondition,
});
export const Weather = IDL.Record({
  'temperature' : IDL.Int,
  'windSpeed' : IDL.Nat,
  'humidity' : IDL.Nat,
  'forecast' : IDL.Vec(ForecastEntry),
  'location' : IDL.Text,
  'condition' : WeatherCondition,
});

export const idlService = IDL.Service({
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAlertsByType' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getResourcesByType' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
  'getWeather' : IDL.Func([], [IDL.Opt(Weather)], ['query']),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertType = IDL.Variant({
    'flood' : IDL.Null,
    'earthquake' : IDL.Null,
    'storm' : IDL.Null,
    'cyclone' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'warning' : IDL.Null,
    'danger' : IDL.Null,
    'safe' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : AlertType,
    'title' : IDL.Text,
    'affectedArea' : IDL.Text,
    'recommendedActions' : IDL.Vec(IDL.Text),
    'affectedPopulation' : IDL.Nat,
    'severity' : Severity,
    'issuedAt' : Timestamp,
    'location' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ResourceType = IDL.Variant({
    'hospital' : IDL.Null,
    'fire' : IDL.Null,
    'supply' : IDL.Null,
    'shelter' : IDL.Null,
    'police' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'resourceType' : ResourceType,
    'address' : IDL.Text,
    'hoursOfOperation' : IDL.Text,
    'phone' : IDL.Text,
  });
  const WeatherCondition = IDL.Variant({
    'cloudy' : IDL.Null,
    'stormy' : IDL.Null,
    'sunny' : IDL.Null,
    'rainy' : IDL.Null,
  });
  const ForecastEntry = IDL.Record({
    'time' : IDL.Text,
    'condition' : WeatherCondition,
  });
  const Weather = IDL.Record({
    'temperature' : IDL.Int,
    'windSpeed' : IDL.Nat,
    'humidity' : IDL.Nat,
    'forecast' : IDL.Vec(ForecastEntry),
    'location' : IDL.Text,
    'condition' : WeatherCondition,
  });
  
  return IDL.Service({
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAlertsByType' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getResourcesByType' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
    'getWeather' : IDL.Func([], [IDL.Opt(Weather)], ['query']),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };