/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'alertType' : AlertType,
  'title' : string,
  'affectedArea' : string,
  'recommendedActions' : Array<string>,
  'affectedPopulation' : bigint,
  'severity' : Severity,
  'issuedAt' : Timestamp,
  'location' : string,
}
export type AlertType = { 'flood' : null } |
  { 'earthquake' : null } |
  { 'storm' : null } |
  { 'cyclone' : null };
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface ForecastEntry {
  'time' : string,
  'condition' : WeatherCondition,
}
export interface Resource {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'name' : string,
  'distanceKm' : number,
  'resourceType' : ResourceType,
  'address' : string,
  'hoursOfOperation' : string,
  'phone' : string,
}
export type ResourceType = { 'hospital' : null } |
  { 'fire' : null } |
  { 'supply' : null } |
  { 'shelter' : null } |
  { 'police' : null };
export type Severity = { 'warning' : null } |
  { 'danger' : null } |
  { 'safe' : null };
export type Timestamp = bigint;
export interface Weather {
  'temperature' : bigint,
  'windSpeed' : bigint,
  'humidity' : bigint,
  'forecast' : Array<ForecastEntry>,
  'location' : string,
  'condition' : WeatherCondition,
}
export type WeatherCondition = { 'cloudy' : null } |
  { 'stormy' : null } |
  { 'sunny' : null } |
  { 'rainy' : null };
export interface _SERVICE {
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAlertsByType' : ActorMethod<[string], Array<Alert>>,
  'getContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getResources' : ActorMethod<[], Array<Resource>>,
  'getResourcesByType' : ActorMethod<[string], Array<Resource>>,
  'getWeather' : ActorMethod<[], [] | [Weather]>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];