/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ForecastEntry {
    time: string;
    condition: WeatherCondition;
}
export interface Weather {
    temperature: bigint;
    windSpeed: bigint;
    humidity: bigint;
    forecast: Array<ForecastEntry>;
    location: string;
    condition: WeatherCondition;
}
export interface ContactSubmission {
    id: bigint;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
}
export interface Resource {
    id: bigint;
    lat: number;
    lng: number;
    name: string;
    distanceKm: number;
    resourceType: ResourceType;
    address: string;
    hoursOfOperation: string;
    phone: string;
}
export interface Alert {
    id: bigint;
    alertType: AlertType;
    title: string;
    affectedArea: string;
    recommendedActions: Array<string>;
    affectedPopulation: bigint;
    severity: Severity;
    issuedAt: Timestamp;
    location: string;
}
export enum AlertType {
    flood = "flood",
    earthquake = "earthquake",
    storm = "storm",
    cyclone = "cyclone"
}
export enum ResourceType {
    hospital = "hospital",
    fire = "fire",
    supply = "supply",
    shelter = "shelter",
    police = "police"
}
export enum Severity {
    warning = "warning",
    danger = "danger",
    safe = "safe"
}
export enum WeatherCondition {
    cloudy = "cloudy",
    stormy = "stormy",
    sunny = "sunny",
    rainy = "rainy"
}
export interface backendInterface {
    getAlerts(): Promise<Array<Alert>>;
    getAlertsByType(alertType: string): Promise<Array<Alert>>;
    getContacts(): Promise<Array<ContactSubmission>>;
    getResources(): Promise<Array<Resource>>;
    getResourcesByType(resourceType: string): Promise<Array<Resource>>;
    getWeather(): Promise<Weather | null>;
    submitContact(name: string, email: string, message: string): Promise<void>;
}
import type { Alert as _Alert, AlertType as _AlertType, ForecastEntry as _ForecastEntry, Resource as _Resource, ResourceType as _ResourceType, Severity as _Severity, Timestamp as _Timestamp, Weather as _Weather, WeatherCondition as _WeatherCondition } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertsByType(arg0: string): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsByType(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsByType(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContacts(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return result;
        }
    }
    async getResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResources();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResources();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesByType(arg0: string): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesByType(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesByType(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeather(): Promise<Weather | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeather();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeather();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AlertType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ForecastEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ForecastEntry): ForecastEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherCondition_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherCondition): WeatherCondition {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Weather_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Weather): Weather {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Weather]): Weather | null {
    return value.length === 0 ? null : from_candid_Weather_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lat: number;
    lng: number;
    name: string;
    distanceKm: number;
    resourceType: _ResourceType;
    address: string;
    hoursOfOperation: string;
    phone: string;
}): {
    id: bigint;
    lat: number;
    lng: number;
    name: string;
    distanceKm: number;
    resourceType: ResourceType;
    address: string;
    hoursOfOperation: string;
    phone: string;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        name: value.name,
        distanceKm: value.distanceKm,
        resourceType: from_candid_ResourceType_n11(_uploadFile, _downloadFile, value.resourceType),
        address: value.address,
        hoursOfOperation: value.hoursOfOperation,
        phone: value.phone
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    temperature: bigint;
    windSpeed: bigint;
    humidity: bigint;
    forecast: Array<_ForecastEntry>;
    location: string;
    condition: _WeatherCondition;
}): {
    temperature: bigint;
    windSpeed: bigint;
    humidity: bigint;
    forecast: Array<ForecastEntry>;
    location: string;
    condition: WeatherCondition;
} {
    return {
        temperature: value.temperature,
        windSpeed: value.windSpeed,
        humidity: value.humidity,
        forecast: from_candid_vec_n16(_uploadFile, _downloadFile, value.forecast),
        location: value.location,
        condition: from_candid_WeatherCondition_n19(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    time: string;
    condition: _WeatherCondition;
}): {
    time: string;
    condition: WeatherCondition;
} {
    return {
        time: value.time,
        condition: from_candid_WeatherCondition_n19(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    alertType: _AlertType;
    title: string;
    affectedArea: string;
    recommendedActions: Array<string>;
    affectedPopulation: bigint;
    severity: _Severity;
    issuedAt: _Timestamp;
    location: string;
}): {
    id: bigint;
    alertType: AlertType;
    title: string;
    affectedArea: string;
    recommendedActions: Array<string>;
    affectedPopulation: bigint;
    severity: Severity;
    issuedAt: Timestamp;
    location: string;
} {
    return {
        id: value.id,
        alertType: from_candid_AlertType_n4(_uploadFile, _downloadFile, value.alertType),
        title: value.title,
        affectedArea: value.affectedArea,
        recommendedActions: value.recommendedActions,
        affectedPopulation: value.affectedPopulation,
        severity: from_candid_Severity_n6(_uploadFile, _downloadFile, value.severity),
        issuedAt: value.issuedAt,
        location: value.location
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hospital: null;
} | {
    fire: null;
} | {
    supply: null;
} | {
    shelter: null;
} | {
    police: null;
}): ResourceType {
    return "hospital" in value ? ResourceType.hospital : "fire" in value ? ResourceType.fire : "supply" in value ? ResourceType.supply : "shelter" in value ? ResourceType.shelter : "police" in value ? ResourceType.police : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cloudy: null;
} | {
    stormy: null;
} | {
    sunny: null;
} | {
    rainy: null;
}): WeatherCondition {
    return "cloudy" in value ? WeatherCondition.cloudy : "stormy" in value ? WeatherCondition.stormy : "sunny" in value ? WeatherCondition.sunny : "rainy" in value ? WeatherCondition.rainy : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flood: null;
} | {
    earthquake: null;
} | {
    storm: null;
} | {
    cyclone: null;
}): AlertType {
    return "flood" in value ? AlertType.flood : "earthquake" in value ? AlertType.earthquake : "storm" in value ? AlertType.storm : "cyclone" in value ? AlertType.cyclone : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    danger: null;
} | {
    safe: null;
}): Severity {
    return "warning" in value ? Severity.warning : "danger" in value ? Severity.danger : "safe" in value ? Severity.safe : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ForecastEntry>): Array<ForecastEntry> {
    return value.map((x)=>from_candid_ForecastEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
